/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorAutomovil;
import javax.swing.JOptionPane;

/**
 *
 * @author Angelica
 */
public class FRM_Automovil extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Automovil
     */
    
    ControladorAutomovil controlador;
    
    public FRM_Automovil() {
        initComponents();
        controlador = new ControladorAutomovil(this);
        this.setLocationRelativeTo(null);
        this.gUI_Botones1.agregarEventos(controlador);
        this.gUI_InfoAutomovil1.agregarEventos(controlador);
        this.estadoInicialBotones();
        this.estadoInicialTxt();
    }
    
    public void estadoInicialTxt(){
        this.gUI_InfoAutomovil1.estadoInicial();
    }
    
    public void estadoInicialBotones(){
        this.gUI_Botones1.estadoInicial();
    }
    
    public void habilitarBotonAgregar(){
        this.gUI_Botones1.habilitarAgregar();
    }
    
    public void habilitarModYElim(){
        this.gUI_Botones1.habilitarModificarYEliminar();
    }  
    
    public void deshabilitarBuscar(){
        this.gUI_InfoAutomovil1.deshabilitarBuscar();
    }
    
    public void limpiarTxt(){
        this.gUI_InfoAutomovil1.limpiarInterfaz();
    }
    
    public void colocarInfo(String arreglo[]){
        this.gUI_InfoAutomovil1.colocarInfo(arreglo);
    }
    
    public String[] devolverInfo(){
        return this.gUI_InfoAutomovil1.devolverInfo();
    }
    
    public void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(null,mensaje);
    }
    
    public String devolverNumRegistro(){
        return this.gUI_InfoAutomovil1.getNumReg();
    }
    
    public void deshabilitarNumRegistro(){
        this.gUI_InfoAutomovil1.deshabilitarNumRegistro();
    }
    
    public void habilitarTxt(){
        this.gUI_InfoAutomovil1.habilitarTxt();
    }
    
      public void mostrarInformacion(String arreglo[]){
        this.gUI_InfoAutomovil1.devolverInfo();
    }
      
     
      
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_InfoAutomovil1 = new Vista.GUI_InfoAutomovil();
        gUI_Botones1 = new Vista.GUI_Botones();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_InfoAutomovil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_InfoAutomovil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Automovil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_InfoAutomovil gUI_InfoAutomovil1;
    // End of variables declaration//GEN-END:variables
}
