/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorAutomovil;

/**
 *
 * @author Angelica
 */
public class GUI_InfoAutomovil extends javax.swing.JPanel {

    /**
     * Creates new form GUI_InfoAutomovil
     */
    
    ControladorAutomovil controlador;
    
    public GUI_InfoAutomovil() {
        initComponents();
    }

    public void agregarEventos(ControladorAutomovil controlador){
        this.controlador=controlador;
        this.btn_Buscar.addActionListener(controlador);
    }
    
    public void deshabilitarBuscar(){
        btn_Buscar.setEnabled(false);
    }
    
    public void limpiarInterfaz(){
        this.jt_NombreDueño.setText("");
        this.jt_NombreDueño.setText("");
        this.jt_Placa.setText("");
    }   
    
    public void estadoInicial(){
        this.jt_NombreDueño.setEnabled(false);
        this.jt_Cedula.setEnabled(false);
        this.jt_Placa.setEnabled(false);
    }
    
    
    public void habilitarTxt(){
        this.jt_NombreDueño.setEnabled(true);
        this.jt_Cedula.setEnabled(true);
        this.jt_Placa.setEnabled(true);
        this.jt_NumeroRegistro.setEnabled(false);
    }
    
     private void presionarEnter(java.awt.event.KeyEvent evt) {                                
        if(evt.getKeyCode()==10){
            controlador.buscar();
        }
    } 
    
    public String[] devolverInfo(){
        String arreglo[];
        arreglo= new String[3];
        arreglo[0]=this.jt_NumeroRegistro.getText();
        arreglo[1]= this.jt_NombreDueño.getText();
        arreglo[2]=this.jt_Cedula.getText();
        arreglo[3]=this.jt_Placa.getText();
        
        return arreglo;
    }
    
    
    public void colocarInfo(String arreglo[]){
        this.jt_NumeroRegistro.setText(arreglo[0]);
        this.jt_NombreDueño.setText(arreglo[1]);
        this.jt_Cedula.setText(arreglo[2]);
        this.jt_Placa.setText(arreglo[3]);     
    }
    
    public String getNumReg(){
        return this.jt_NumeroRegistro.getText();
    }
    
    
    public void deshabilitarNumRegistro(){
        this.jt_NumeroRegistro.setEnabled(false);
    }
 
    
     public void colocarNumReg() {
        this.jt_NumeroRegistro.setText(controlador.numRegistro());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jt_NumeroRegistro = new javax.swing.JTextField();
        jt_NombreDueño = new javax.swing.JTextField();
        jt_Cedula = new javax.swing.JTextField();
        jt_Placa = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Registro Automóvil");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Número de Registro:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Nombre del Dueño:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Cédula del Dueño:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Placa del Automóvil:");

        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscar.png"))); // NOI18N
        btn_Buscar.setActionCommand("Buscar");
        btn_Buscar.setContentAreaFilled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jt_NumeroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Buscar))
                            .addComponent(jt_NombreDueño, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jt_Placa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(jt_Cedula, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jt_NumeroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btn_Buscar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_NombreDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_NombreDueño;
    private javax.swing.JTextField jt_NumeroRegistro;
    private javax.swing.JTextField jt_Placa;
    // End of variables declaration//GEN-END:variables
}
